### ISSUE TITLE
NullReferenceException when using XUnit but not XUnit assertions

### ISSUE THREAD

**Issue by blairconrad** [approvals/ApprovalTests.Net#159]
I've a project that uses XUnit (2) as the testing framework, but FluentAssertions for assertions. As such, we don't include xunit.assertions in the build.

When we have objects that don't match, and no better reporters available, `Approvals.Verify` eventually attempts to use `XUnitReporter` to report, because it found that XUnit `IsWorkingInThisEnvironment`. This eventually leads `AssertReporter.AssertEqual` to attempt to [find the type](https://github.com/approvals/ApprovalTests.Net/blob/129fdb100e92d8f3b1839ee675cb4d3e03baeabc/ApprovalTests/Reporters/AssertReporter.cs#L47) "Xunit.Assert, xunit". It can't find this, so eventually `XUnitReporter.InvokeEqualsMethod` is passed a `null` type, and `type.GetMethods` [throws](https://github.com/approvals/ApprovalTests.Net/blob/129fdb100e92d8f3b1839ee675cb4d3e03baeabc/ApprovalTests/Reporters/XUnitReporter.cs#L17) a `NullReferenceException`:

```
move /Y "C:\PortableApps\Documents\Source\GitHub\FakeItEasy\tests\FakeItEasy.Tests.Approval\ApiApproval.ApproveApi.received.txt" "C:\PortableApps\Documents\Source\GitHub\FakeItEasy\tests\FakeItEasy.Tests.Approval\ApiApproval.ApproveApi.approved.txt"
   FakeItEasy.Tests.Approval.ApiApproval.ApproveApi [FAIL]
      System.NullReferenceException : Object reference not set to an instance of an object.
      Stack Trace:
            at ApprovalTests.Reporters.XUnitReporter.InvokeEqualsMethod(Type type, String[] parameters)
            at ApprovalTests.Reporters.AssertReporter.AssertEqual(String approvedContent, String receivedContent)
            at ApprovalTests.Reporters.AssertReporter.AssertFileContents(String approved, String received)
            at ApprovalTests.Reporters.AssertReporter.Report(String approved, String received)
            at ApprovalTests.Reporters.FirstWorkingReporter.Report(String approved, String received)
            at ApprovalTests.Reporters.FirstWorkingReporter.Report(String approved, String received)
            at ApprovalTests.Approvers.FileApprover.ReportFailure(IApprovalFailureReporter reporter)
            at ApprovalTests.Core.Approver.Verify(IApprovalApprover approver, IApprovalFailureReporter reporter)
            at ApprovalTests.Approvals.Verify(IApprovalWriter writer, IApprovalNamer namer, IApprovalFailureReporter reporter)
            at ApprovalTests.Approvals.Verify(IApprovalWriter writer)
            at ApprovalTests.Approvals.Verify(String text)
         tests\FakeItEasy.Tests.Approval\ApiApproval.cs(16,0): at FakeItEasy.Tests.Approval.ApiApproval.ApproveApi()
```

This raises a few questions:
1. shouldn't we be running `XUnit2Reporter`? Unfortunately, it's not hooked up in `FrameworkAssertReporter`. I'm happy to raise another issue for this, if you like.
2. Often people using a unit testing framework will use that framework's assertions, but it seems that the trend to use an external assertion library is rising. Is there interest in having ApprovalTests attempt to use such assertion libraries if present, instead of the unit testing framework? Especially when the presence of the testing framework does not guarantee that _its_ assertion library is available?
3. If there's no interest in 2, or even if so, perhaps we could detect the inability to find the type that the assertion is expected to live on and provide a more obvious error message?

I'm happy to work on any or all of these potential issues, but didn't want to start barging in with PRs without finding which direction you'd like to go.

Otherwise, I'm enjoying ApprovalTests. Thanks for the library!

**Comment by stefc** [comment]
We have the same issue in a TeamCity CI environment

**Comment by SimonCropp** [comment]
my work around

```
        var reporters = (IEnvironmentAwareReporter[])FrameworkAssertReporter.INSTANCE.Reporters;
        reporters[2] = XUnit2Reporter.INSTANCE;
```

but i think xunit 1 support should be dropped. xunit 2 is 3 yrs old now

ping @isidore

**Comment by SimonCropp** [comment]
@isidore want a PR for this?

**Comment by SimonCropp** [comment]
this should be fixed as part of https://github.com/approvals/ApprovalTests.Net/pull/262

**Comment by emilybache** [comment]
Hi, I just ran into this issue with a team and I'm very pleased to see that there is both a fix in the works and a workaround. I'm not much of a .net whizz and I couldn't really work out how to use the workaround. Where am I supposed to put the code snippet mentioned by @SimonCropp ?

Also, does anyone have any guess when the 3.1.0 milestone will be available in Nuget?

**Comment by isidore** [comment]
Will try to release today

**Comment by emilybache** [comment]
Thanks!

**Comment by blairconrad** [comment]
Hi, owners. I may be missing something, but I think there's a regression, or the issue was not fully fixed.

Yesterday I pushed a new FakeItEasy commit. It turns out there was an API diff (although it looks like it's just line endings in the file - I'll have to investigate that) and it failed [with a NullReferenceException](https://ci.appveyor.com/project/blairconrad/fakeiteasy/builds/28743698/job/j69liqxbjuqxxqxi#L451) as it did the first time I reported this issue. Note that our test project references xunit.core but not xunit.assert.
As soon as I reference xunit.assert, my test still fails, but [the assertion performs correctly](https://ci.appveyor.com/project/blairconrad/fakeiteasy/builds/28748529/job/vnp100g0vwlvwueb#L453).

In #262, @SimonCropp changed `XUnit2Reporter.IsXunit2` to be true if [either xunit.core or xunit.assert is loaded in the current domain](https://github.com/approvals/ApprovalTests.Net/pull/262/files#diff-7b393df72b9eee7874c3eb38951312a5R19-R23).

I don't profess to be an expert, but I think this is too lenient, since `XUnit2Reporter.XUnit2Reporter` requires "xunit.assert" to be loaded, if I read it correctly. Is there a reason not to insist on xunit.assert before considering XUnit2Reporter to be available?

Thanks for all your hard work.
